### Non linear system


$$I\cdot\dot{\omega} = (I\cdot\omega) \times \omega + \tau$$


Rewritten as:

$$\dot{x} = A(x)x+u$$

$$A(x) =
\begin{pmatrix}
0 & I_3*x_3 & 0 \\
0 & 0 & I_1*x_1 \\
I_2*x_2 & 0 & 0
\end{pmatrix}$$

with $u = [u_1 u_2 u_3]^T$

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

In [117]:
# Initialize weights and bias

def initialize_parameters(n_input,n_output,n_hidden):
    parameters = {}
    parameters["W1"] = np.random.randn(n_hidden,n_input)
    parameters["b1"] = np.zeros((n_hidden,1))
    parameters["W2"] = np.random.randn(n_output,n_hiden)
    parameters["b2"] = np.zeros((n_output,1))
    parameters["I"] = np.zeros((1,1))
    parameters["D"] = np.zeros((1,1))
    return parameters

In [118]:
## activation functions

def p_neuron(v):
    v[v>= 1] = 1
    v[v<=-1] = -1
    return v

def i_neuron(v,I):
    v = v + I
    v[v>=1]=1
    v[v<=-1]=-1
    return v

def d_neuron(v,D):
    v = v - D
    v[v>=1]=1
    v[v<=-1]=-1
    return D

In [120]:
def forward_propagation(X,parameters):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    I  = parameters["I"]
    D  = parameters["D"]
    
    
    X= np.reshape(X,(X.shape[1],-1))
     
    Z1 = np.dot(W1,X)+b1
    P = p_neuron(Z1[0])
    I = i_neuron(Z1[1],I)
    D = d_neuron(Z1[2],D)
    A1 = np.concatenate((P,I,D),axis=0)
    A1 = A1.reshape(A1.shape[0],-1)
    Z2 = np.dot(W1,A1)+b2
    A2 = p_neuron(Z2)
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2,
             "I": I,
             "D": D}
    
    return cache

In [121]:
## Compute cost

def compute_cost(A2,Y):
    m=Y.shape[1]
    J = 1/m * np.dot((A2 - Y),(A2-Y).T)

In [92]:
def compute_cost(A2,Y):
    m=Y.shape[1]
    J = 1/m * np.dot((A2 - Y),(A2-Y).T)

array([array([0.03882794]), array([-0.02805731]), 0], dtype=object)

In [115]:
# backprop

def back_pneuron():
    pass

def back_ineuron():
    pass

def bac_dneuron():
    pass


In [3]:
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
A[0,1] = 5

In [9]:
x = np.random.rand(3,1)

In [14]:
x[1][0]

array([0.46597732])